apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: "{{- printf "Host(`%s`)" .Values.adminDomain }}"
      services:
        - name: keycloak-http
          port: http
    - kind: Rule
      match: "{{- printf "Host(`%s`)" .Values.ssoDomain }}"
      services:
        - name: keycloak-http
          port: http
  tls:
    domains:
      - main: "{{ .Values.adminDomain }}"
      - main: "{{ .Values.ssoDomain }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak
stringData:
  KEYCLOAK_USER: c9c
  KEYCLOAK_PASSWORD: "{{.Values.secrets.keycloak_password }}"
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: "{{.Values.secrets.keycloak_password }}"
  KC_HOSTNAME: "https://{{.Values.ssoDomain}}"
  KC_HOSTNAME_ADMIN: "https://{{.Values.adminDomain}}"
  KC_CACHE_CONFIG_FILE: cache-ispn-jdbc-ping.xml
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres
stringData:
  admin-password: "{{.Values.secrets.postgress_password }}"
  postgres-password: "{{.Values.secrets.postgress_password }}"
  password: "{{.Values.secrets.postgress_password }}"
  repmgr-password: "{{.Values.secrets.postgress_password }}"

