################################################################################
# Copyright ContinuousC. Licensed under the "Elastic License 2.0".             #
################################################################################

version: v2beta1
name: continuousc-chart

pullSecrets:
  gitea:
    registry: gitea.contc

deployments:
  continuousc-chart:
    helm:
      displayOutput: true
      chart:
        path: .
      releaseName: continuousc
      values:
        continuousc:
          registry: "gitea.contc/continuousc"
          tenant: ${TENANT}
          prometheusTenant: ${USER}-${TENANT}
          domain: continuousc.contc
          auth:
            subDomain: ${USER}-app
            namespace: auth-${USER}
          sso:
            realm: ${USER}
      upgradeArgs:
        - "--post-renderer=argocd-vault-plugin.sh"
        - "--post-renderer-args=-"
      templateArgs:
        - "--post-renderer=argocd-vault-plugin.sh"
        - "--post-renderer-args=-"
