################################################################################
# Copyright ContinuousC. Licensed under the "Elastic License 2.0".             #
################################################################################

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jaeger-anomaly-detection
  labels:
    app.kubernetes.io/name: jaeger-anomaly-detection
    app.kubernetes.io/instance: {{ .Release.Name }}
    tenant: {{ .Values.continuousc.tenant }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jaeger-anomaly-detection
      app.kubernetes.io/instance: {{ .Release.Name }}
      tenant: {{ .Values.continuousc.tenant }}
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jaeger-anomaly-detection
        app.kubernetes.io/instance: {{ .Release.Name }}
        tenant: {{ .Values.continuousc.tenant }}
    spec:
      containers:
        - name: jaeger-anomaly-detection
          imagePullPolicy: Always
          image: "{{ required "missing registry name" .Values.continuousc.registry }}/{{ .Values.continuousc.c9c.jaegerAnomalyDetection.image }}:{{ .Values.continuousc.c9c.jaegerAnomalyDetection.tag }}"
          command:
            - "/usr/bin/jaeger-anomaly-detection-engine"
            - --state=/var/lib/jaeger-anomaly-detection/state.cbor
            - --opensearch-ca=/etc/opensearch/tls/ca.crt
            - --opensearch-cert=/etc/opensearch/tls/tls.crt
            - --opensearch-key=/etc/opensearch/tls/tls.key
            - --opensearch-url=https://opensearch-cluster-master:9200
            - --prometheus-url=http://cortex-distributor.cortex:8080/api/v1/push
            - "--prometheus-tenant={{ .Values.continuousc.prometheusTenant }}"
            - --bind=0.0.0.0:80
          env:
            - name: "RUST_BACKTRACE"
              value: "1"
            - name: "RUST_LOG"
              value: "debug"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: jaeger-anomaly-detection-state
              mountPath: /var/lib/jaeger-anomaly-detection
            - name: opensearch-admin
              readOnly: true
              mountPath: /etc/opensearch/tls
          resources:
            requests:
              cpu: 0.1
              memory: "512Mi"
      imagePullSecrets:
        - name: private-registry
      volumes:
        - name: jaeger-anomaly-detection-state
          persistentVolumeClaim:
            claimName: jaeger-anomaly-detection-state
        - name: opensearch-admin
          secret:
            secretName: opensearch-admin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jaeger-anomaly-detection-state
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500M
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-anomaly-detection
  labels:
    app.kubernetes.io/name: jaeger-anomaly-detection
    app.kubernetes.io/instance: {{ .Release.Name }}
    tenant: {{ .Values.continuousc.tenant }}
spec:
  type: ClusterIP
  ports:
    - name: http
      targetPort: http
      protocol: TCP
      port: 80
  selector:
    app.kubernetes.io/name: jaeger-anomaly-detection
    app.kubernetes.io/instance: {{ .Release.Name }}
    tenant: {{ .Values.continuousc.tenant }}
