################################################################################
# Copyright ContinuousC. Licensed under the "Elastic License 2.0".             #
################################################################################

apiVersion: v1
kind: Secret
metadata:
  name: opensearch-internal-users
  annotations:
    avp.kubernetes.io/path: "kv/data/continuousc/{{ .Values.continuousc.tenant }}"
type: Opaque
stringData:
  internal_users.yml: |
    _meta:
      type: "internalusers"
      config_version: 2
    admin:
      description: "ContinuousC admin user"
      hash: "<opensearch-admin-hash-password>"
      reserved: true
      backend_roles:
        - "admin"
