################################################################################
# Copyright ContinuousC. Licensed under the "Elastic License 2.0".             #
################################################################################

apiVersion: v1
kind: Secret
metadata:
  name: opensearch-admin-password
  annotations:
    avp.kubernetes.io/path: "kv/data/continuousc/{{ .Values.continuousc.tenant }}"
type: Opaque
stringData:
  {{ if .Values.continuousc.secrets.opensearch-admin-password }}
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: "{{ .Values.continuousc.secrets.opensearch-admin-password }}"
  {{ else }}
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: "<opensearch-admin-password>"
  {{ end }}
