################################################################################
# Copyright ContinuousC. Licensed under the "Elastic License 2.0".             #
################################################################################

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgresql
  annotations:
    avp.kubernetes.io/path: "kv/data/continuousc/{{ .Values.continuousc.tenant }}"
stringData:
  password: "<postgresql-user-password>"
