################################################################################
# Copyright ContinuousC. Licensed under the "Elastic License 2.0".             #
################################################################################

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: continuousc
subjects:
  - kind: ServiceAccount
    name: continuousc
roleRef:
  kind: Role
  name: continuousc
  apiGroup: rbac.authorization.k8s.io
