ssoDomain: sso.continuousc.com
adminDomain: admin-sso.continuousc.com
secrets:
  keycloak_password: ""
  postgress_password: ""

keycloakx:
  fullnameOverride: keycloak
  image:
    repository: quay.io/phasetwo/phasetwo-keycloak
    tag: 25.0.2
  command:
    - "/opt/keycloak/bin/kc.sh"
    - "start"
  args:
    - "--spi-email-template-provider=freemarker-plus-mustache"
    - "--spi-email-template-freemarker-plus-mustache-enabled=true"
    - "--spi-theme-cache-themes=false"
  http:
    relativePath: "/"
  database:
    vendor: postgres
    hostname: keycloak-pgpool
    port: 5432
    database: keycloak
    username: keycloak
    existingSecret: postgres
    existingSecretKey: password
  extraEnvFrom: |-
    - secretRef:
        name: keycloak    
  extraEnv: |
    - name: JAVA_OPTS_APPEND
      value: >-
        -Djgroups.dns.query=keycloak-headless
    - name: JAVA_OPTS
      value: >-
        -XX:+UseContainerSupport
        -XX:MaxRAMPercentage=50.0
        -Djava.net.preferIPv4Stack=true
        -Djava.awt.headless=true
    - name: KC_DB_POOL_MAX_SIZE
      value: "10"    
  serviceAccount:
    create: false

postgresql-ha:
  fullnameOverride: keycloak
  global:
    postgresql:
      database: keycloak
      username: keycloak
      repmgrUsername: keycloak
      repmgrDatabase: keycloak
      existingSecret: postgres
    pgpool:
      adminUsername: keycloak
      existingSecret: postgres
  pgpool:
    numInitChildren: "33"
    maxPool: "1"
