config:
  auth_enabled: true
  api:
    response_compression_enabled: true
  alertmanager:
    enable_api: true
  ruler:
    enable_api: true
  frontend:
    log_queries_longer_than: 1s
    # compress_responses: true
  querier:
    timeout: "30s"
    max_samples: 1000000
  query_range:
    # split_queries_by_interval: 24h
    # align_queries_with_step: true
    # cache_results: true
    results_cache:
      cache:
        memcached_client:
          timeout: "10s"
  store_gateway:
  blocks_storage:
    backend: "s3"
    s3:
      endpoint: "minio.cortex:443"
      bucket_name: "cortex"
      access_key_id: "<access_key_id>"
      secret_access_key: "<secret_access_key>"
      http:
        insecure_skip_verify: true
    bucket_store:
      index_cache:
        memcached:
          timeout: "10s"
      chunks_cache:
        memcached:
          timeout: "10s"
      metadata_cache:
        memcached:
          timeout: "10s"
  alertmanager_storage:
    backend: "s3"
    s3:
      endpoint: "minio.cortex:443"
      bucket_name: "alertmanager"
      access_key_id: "<access_key_id>"
      secret_access_key: "<secret_access_key>"
      http:
        insecure_skip_verify: true
    # backend: local
    # local:
    #   path: /data
  ruler_storage:
    backend: "s3"
    s3:
      endpoint: "minio.cortex:443"
      bucket_name: "ruler"
      access_key_id: "<access_key_id>"
      secret_access_key: "<secret_access_key>"
      http:
        insecure_skip_verify: true
    # backend: local
    # local:
    #   directory: /data/rules
  server:
    grpc_server_max_recv_msg_size: 52428800
    grpc_server_max_send_msg_size: 52428800
  ingester_client:
    grpc_client_config:
      max_recv_msg_size: 52428800
      max_send_msg_size: 52428800
runtimeconfigmap:
  runtime_config:
    ingester_limits:
      max_ingestion_rate: 1000000
    overrides:
      fake:
        ingestion_rate: 1000000
        max_series_per_metric: 200000
      mdp-demo:
        ingestion_rate: 1000000
        max_series_per_metric: 200000
      abo-demo:
        ingestion_rate: 1000000
        max_series_per_metric: 200000
      demo:
        ingestion_rate: 1000000
        max_series_per_metric: 200000
ingester:
  resources:
    requests:
      memory: 2G
      cpu: 0.3
    limits:
      memory: 15G
  statefulSet:
    enabled: true
alertmanager:
  statefulSet:
    enabled: true
  extraVolumes:
    - name: tmp
      emptyDir: {}
  extraVolumeMounts:
    - name: tmp
      mountPath: /tmp
distributor:
  resources:
    requests:
      memory: 2G
      cpu: 0.3
    limits:
      memory: 5G
store_gateway:
  resources:
    requests:
      memory: 2G
      cpu: 0.3
    limits:
      memory: 5G
querier:
  extraArgs:
    api.build-info-enabled: true
    experimental.alertmanager.enable-api: true
    experimental.ruler.enable-api: true
  resources:
    requests:
      memory: 2G
      cpu: 0.3
    limits:
      memory: 5G
query_frontend:
  extraArgs:
    api.build-info-enabled: true
    experimental.alertmanager.enable-api: true
    experimental.ruler.enable-api: true
memcached-frontend:
  enabled: true
memcached-blocks-index:
  enabled: true
memcached-blocks-metadata:
  enabled: true
memcached-blocks:
  enabled: true
